[package]
    name = "learn-libp2p-rust"
    version = "0.1.0"
    authors = ["Lee Dogeon <dev.moreal@gmail.com>"]
    edition = "2021"
    rust-version = "1.56.1"

[dependencies]
    libp2p = "0.43.0"
    futures = "0.3.21"
    async-std = { version = "1.10.0", features = ["attributes"] }
